name: Test Project React 2
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v3
      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: |
          cd react-app
          npm install
        working-directory: gitActions
      - name: Test
        run: npm run test
